backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: master
slug:
  encoding: "ascii"
  clean_accents: true
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "article"
    label: "Article"
    folder: "data/articles"
    create: true
    sort: "date:asc"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Brève", name: "excerpt", widget: "text"}
      - {label: "Image principale de l’article", name: "thumbnail", widget: "image"}
      - {label: "Crédits de l’image principale", name: "thumbnailCredits", widget: "text", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Mots clés", name: "tags", widget: "list", required: false}
      - {label: "Date de publication", name: "date", widget: "datetime"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Foire aux questions"
        name: "faqs"
        file: "data/faqs/faqs.json"
        fields:
          - name: "entries"
            label: "Entrées"
            widget: list
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Réponse", name: "answer", widget: "markdown"}
